alias nab="nano ~/.bashrc"
alias cl="clear"
# git
alias gad="git add"
alias gbr="git branch"
alias gci="git commit -m"
alias gco="git checkout"
alias gfe="git fetch origin"
alias gpl="git pull"
alias gpp="git stash pop"
alias gpu="git push"
alias gsh="git stash -m"
alias gshl="git stash list"
alias gst="git status"
alias gsw="git switch"
# dev
alias npm-dev="npm run dev"
alias npm-sb="npm run storybook"
alias npi="npm install"
alias npui="npm uninstall"
